### ISSUE TITLE
cluster.ft functions missing after upgrading to V5

### ISSUE THREAD

**Issue by alexchaoss** [redis/node-redis#3064]
### Description

I didn't see anything about this in the migration documents, but after upgrading to V5 I only have a limited access to the search functions (some aggregate functions and suggestion functions), but functions such as create, search, _list and most other functions are not exposed anymore with cluster type.

Am I missing something?

For exemple `client.ft.search` is defined but `cluster.ft.search` is not.

### Node.js Version

22

### Redis Server Version

7.0.2

### Node Redis Version

5.8.2

### Platform

macOS

### Logs

```bash
Property 'create' does not exist on type '{ _LIST: CommandSignature<{ readonly NOT_KEYED_COMMAND: true; readonly IS_READ_ONLY: true; readonly parseCommand: (this: void, parser: CommandParser) => void; readonly transformReply: { readonly 2: () => ArrayReply<...>; readonly 3: () => SetReply<...>; }; }, 2, {}>; ... 66 more ...; tagVals: CommandSignature<...>; ...'.
  Property 'create' does not exist on type '{ AGGREGATE_WITHCURSOR: CommandSignature<{ readonly IS_READ_ONLY: false; readonly parseCommand: (this: void, parser: CommandParser, index: RedisArgument, query: RedisArgument, options?: FtAggregateWithCursorOptions | undefined) => void; readonly transformReply: { ...; }; readonly unstableResp3: true; }, 2, {}>; ... ...'.ts(2339)
```

**Comment by nkaradzhov** [comment]
Hi @alexchaoss, thanks for raising this issue. It looks like a typescript regression that was introduced in v5. I will have a look into it.

**Comment by simonprickett** [comment]
I think I might be seeing similar with bloom commands - try using the topk example from the examples folder but swap `createClient` for `createClientPool` and you see errors like this:

```
topk % node topk.js
Error, maybe RedisBloom is not installed?:
TypeError: Cannot read properties of undefined (reading 'reserve')
    at file:///Users/simon/tmp/topk/topk.js:18:21
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
file:///Users/simon/tmp/topk/topk.js:51
  await client.topK.incrBy('mytopk', {
                    ^

TypeError: Cannot read properties of undefined (reading 'incrBy')
    at file:///Users/simon/tmp/topk/topk.js:51:21
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

works fine with `createClient`.  Redis Stack latest docker image:

```
 % redis-cli info server
# Server
redis_version:7.4.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b6b2e66014f8e765
redis_mode:standalone
os:Linux 6.10.14-linuxkit x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:11.4.0
process_id:10
process_supervised:no
run_id:d311a10e9a181a87eb424d24bdc8b84c57e013ec
tcp_port:6379
server_time_usec:1756214383481777
uptime_in_seconds:3012
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:11383919
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0
listener0:name=tcp,bind=*,bind=-::*,port=6379
```

**Comment by simonprickett** [comment]
Was this not fixed in 5.8.3, the stock Top-K example from the examples folder still fails on a Redis Stack database:

```
127.0.0.1:6379> info modules
# Modules
module:name=search,ver=21020,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=timeseries,ver=11206,api=1,filters=0,usedby=[],using=[],options=[]
module:name=redisgears_2,ver=20020,api=1,filters=0,usedby=[],using=[],options=[]
module:name=RedisCompat,ver=1,api=1,filters=0,usedby=[],using=[],options=[]
module:name=ReJSON,ver=20809,api=1,filters=0,usedby=[search],using=[],options=[handle-io-errors]
module:name=bf,ver=20807,api=1,filters=0,usedby=[],using=[],options=[]
```

```
topk % node topk.js
Error, maybe RedisBloom is not installed?:
TypeError: Cannot read properties of undefined (reading 'reserve')
    at file:///Users/simon/tmp/topk/topk.js:18:21
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
file:///Users/simon/tmp/topk/topk.js:51
  await client.topK.incrBy('mytopk', {
                    ^

TypeError: Cannot read properties of undefined (reading 'incrBy')
    at file:///Users/simon/tmp/topk/topk.js:51:21
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
