### ISSUE TITLE
After Upgrade to 7.1.0 with legacy mode getting client.hset is not a function

### ISSUE THREAD

**Issue by djaffer** [redis/node-redis#1760]
I have a legacy mode on, yet I keep getting this message. 

Do I need to connect after every command?

Will be downgrading to the previous version due to the lack of smooth migration and breakage. 

Also, the deprecation of auto-connect implies that it should be done once you create a connection then you connect once or before every command, which we must do. With a legacy mode as true that feature does come back?

**Comment by djaffer** [comment]
It was due to the change to the camel case. This is a very destructive change even with legacy support on it is failing.
