### ISSUE TITLE
Redis tsc compile error

### ISSUE THREAD

**Issue by alishah730** [redis/node-redis#2256]
Redis typescript build is throwing compilation error 

Steps to reproduce:
1. create a simple ts file with any simple redis function
2. add redis dependency
3. execute tsc command and it will throwing below error

```
9     context: RedisCommandArgument,
             ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:10:6 - error TS1005: ',' expected.

10     _: RedisCommandArgument,
        ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:11:11 - error TS1005: ',' expected.

11     object: RedisCommandArgument,
             ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:12:6 - error TS1005: ',' expected.

12     _: RedisCommandArgument,
        ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:13:13 - error TS1005: ',' expected.

13     username: RedisCommandArgument,
               ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:14:6 - error TS1005: ',' expected.

14     _: RedisCommandArgument,
        ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:15:15 - error TS1005: ',' expected.

15     ageSeconds: RedisCommandArgument,
                 ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:16:6 - error TS1005: ',' expected.

16     _: RedisCommandArgument,
        ~

../node_modules/@redis/client/dist/lib/commands/ACL_LOG.d.ts:17:15 - error TS1005: ',' expected.

17     clientInfo: RedisCommandArgument
                 ~

../node_modules/@redis/client/dist/lib/commands/BITFIELD.d.ts:2:40 - error TS1110: Type expected.

2 export declare type BitFieldEncoding = `${'i' | 'u'}${number}`;
                                         ~~~

../node_modules/@redis/client/dist/lib/commands/BZPOPMAX.d.ts:5:36 - error TS1005: ',' expected.

5 declare type ZMemberRawReply = [key: RedisCommandArgument, value: RedisCommandArgument, score: RedisCommandArgument] | null;
                                     ~

../node_modules/@redis/client/dist/lib/commands/BZPOPMAX.d.ts:5:65 - error TS1005: ',' expected.

5 declare type ZMemberRawReply = [key: RedisCommandArgument, value: RedisCommandArgument, score: RedisCommandArgument] | null;
                                                                  ~

../node_modules/@redis/client/dist/lib/commands/BZPOPMAX.d.ts:5:94 - error TS1005: ',' expected.

5 declare type ZMemberRawReply = [key: RedisCommandArgument, value: RedisCommandArgument, score: RedisCommandArgument] | null;
                                                                                               ~

../node_modules/@redis/client/dist/lib/commands/CLIENT_KILL.d.ts:14:14 - error TS1110: Type expected.

14     address: `${string}:${number}`;
                ~~~

../node_modules/@redis/client/dist/lib/commands/CLIENT_KILL.d.ts:15:1 - error TS1128: Declaration or statement expected.

15 }
   ~

../node_modules/@redis/client/dist/lib/commands/CLIENT_KILL.d.ts:17:19 - error TS1110: Type expected.

17     localAddress: `${string}:${number}`;
                     ~~~

../node_modules/@redis/client/dist/lib/commands/CLIENT_KILL.d.ts:18:1 - error TS1128: Declaration or statement expected.

18 }
   ~

../node_modules/@redis/client/dist/lib/commands/CLIENT_KILL.d.ts:20:18 - error TS1110: Type expected.

20     id: number | `${number}`;
                    ~~~

../node_modules/@redis/client/dist/lib/commands/CLIENT_KILL.d.ts:21:1 - error TS1128: Declaration or statement expected.

21 }
   ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:3:39 - error TS1005: ',' expected.

3 declare type ClusterSlotsRawNode = [ip: string, port: number, id: string];
                                        ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:3:53 - error TS1005: ',' expected.

3 declare type ClusterSlotsRawNode = [ip: string, port: number, id: string];
                                                      ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:3:65 - error TS1005: ',' expected.

3 declare type ClusterSlotsRawNode = [ip: string, port: number, id: string];
                                                                  ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:5:9 - error TS1005: ',' expected.

5     from: number,
          ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:6:7 - error TS1005: ';' expected.

6     to: number,
        ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:7:11 - error TS1005: ';' expected.

7     master: ClusterSlotsRawNode,
            ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:8:5 - error TS1109: Expression expected.

8     ...replicas: Array<ClusterSlotsRawNode>
      ~~~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:9:1 - error TS1005: '(' expected.

9 ]>;
  ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:9:2 - error TS1109: Expression expected.

9 ]>;
   ~

../node_modules/@redis/client/dist/lib/commands/CLUSTER_SLOTS.d.ts:9:3 - error TS1109: Expression expected.

9 ]>;
    ~

../node_modules/@redis/client/dist/lib/commands/CONFIG_SET.d.ts:2:42 - error TS1005: ',' expected.

2 declare type SingleParameter = [parameter: RedisCommandArgument, value: RedisCommandArgument];
                                           ~

../node_modules/@redis/client/dist/lib/commands/CONFIG_SET.d.ts:2:71 - error TS1005: ',' expected.

2 declare type SingleParameter = [parameter: RedisCommandArgument, value: RedisCommandArgument];
                                                                        ~

../node_modules/@redis/client/dist/lib/commands/CONFIG_SET.d.ts:3:42 - error TS1005: ',' expected.

3 declare type MultipleParameters = [config: Record<string, RedisCommandArgument>];
                                           ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:10:6 - error TS1005: ',' expected.

10     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:11:11 - error TS1005: ',' expected.

11     server: RedisCommandArgument,
             ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:12:6 - error TS1005: ',' expected.

12     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:13:12 - error TS1005: ',' expected.

13     version: RedisCommandArgument,
              ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:14:6 - error TS1005: ',' expected.

14     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:15:10 - error TS1005: ',' expected.

15     proto: number,
            ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:16:6 - error TS1005: ',' expected.

16     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:17:7 - error TS1005: ',' expected.

17     id: number,
         ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:18:6 - error TS1005: ',' expected.

18     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:19:9 - error TS1005: ',' expected.

19     mode: RedisCommandArgument,
           ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:20:6 - error TS1005: ',' expected.

20     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:21:9 - error TS1005: ',' expected.

21     role: RedisCommandArgument,
           ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:22:6 - error TS1005: ',' expected.

22     _: never,
        ~

../node_modules/@redis/client/dist/lib/commands/HELLO.d.ts:23:12 - error TS1005: ',' expected.

23     modules: Array<RedisCommandArgument>
              ~

../node_modules/@redis/client/dist/lib/commands/HSET.d.ts:7:37 - error TS1005: ',' expected.

7 declare type GenericArguments = [key: RedisCommandArgument];
                                      ~

../node_modules/@redis/client/dist/lib/commands/HSET.d.ts:8:48 - error TS1005: ',' expected.

8 declare type SingleFieldArguments = [...generic: GenericArguments, field: Types, value: Types];
                                                 ~

../node_modules/@redis/client/dist/lib/commands/HSET.d.ts:8:73 - error TS1005: ',' expected.

8 declare type SingleFieldArguments = [...generic: GenericArguments, field: Types, value: Types];
                                                                          ~

../node_modules/@redis/client/dist/lib/commands/HSET.d.ts:8:87 - error TS1005: ',' expected.

8 declare type SingleFieldArguments = [...generic: GenericArguments, field: Types, value: Types];
                                                                                        ~

../node_modules/@redis/client/dist/lib/commands/HSET.d.ts:9:51 - error TS1005: ',' expected.

9 declare type MultipleFieldsArguments = [...generic: GenericArguments, value: HSETObject | HSETMap | HSETTuples];
                                                    ~

../node_modules/@redis/client/dist/lib/commands/HSET.d.ts:9:76 - error TS1005: ',' expected.

9 declare type MultipleFieldsArguments = [...generic: GenericArguments, value: HSETObject | HSETMap | HSETTuples];
                                                                             ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX.d.ts:8:13 - error TS1005: ',' expected.

8         key1: RawRangeReply,
              ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX.d.ts:9:13 - error TS1005: ',' expected.

9         key2: RawRangeReply
              ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX.d.ts:10:6 - error TS1005: ';' expected.

10     ]>,
        ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX.d.ts:10:7 - error TS1109: Expression expected.

10     ]>,
         ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX.d.ts:13:1 - error TS1128: Declaration or statement expected.

13 ];
   ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX_WITHMATCHLEN.d.ts:8:13 - error TS1005: ',' expected.

8         key1: RawRangeReply,
              ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX_WITHMATCHLEN.d.ts:9:13 - error TS1005: ',' expected.

9         key2: RawRangeReply,
              ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX_WITHMATCHLEN.d.ts:10:15 - error TS1005: ',' expected.

10         length: number
                 ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX_WITHMATCHLEN.d.ts:11:6 - error TS1005: ';' expected.

11     ]>,
        ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX_WITHMATCHLEN.d.ts:11:7 - error TS1109: Expression expected.

11     ]>,
         ~

../node_modules/@redis/client/dist/lib/commands/LCS_IDX_WITHMATCHLEN.d.ts:14:1 - error TS1128: Declaration or statement expected.

14 ];
   ~

../node_modules/@redis/client/dist/lib/commands/LMPOP.d.ts:6:8 - error TS1005: ',' expected.

6     key: string,
         ~

../node_modules/@redis/client/dist/lib/commands/LMPOP.d.ts:7:13 - error TS1005: ',' expected.

7     elements: Array<string>
              ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:6:12 - error TS1005: ',' expected.

6     pending: number,
             ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:7:12 - error TS1005: ',' expected.

7     firstId: RedisCommandArgument | null,
             ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:8:11 - error TS1005: ',' expected.

8     lastId: RedisCommandArgument | null,
            ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:9:14 - error TS1005: ',' expected.

9     consumers: Array<[
               ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:10:13 - error TS1005: ',' expected.

10         name: RedisCommandArgument,
               ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:11:26 - error TS1005: ',' expected.

11         deliveriesCounter: RedisCommandArgument
                            ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:12:6 - error TS1005: ';' expected.

12     ]> | null
        ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:12:8 - error TS1109: Expression expected.

12     ]> | null
          ~

../node_modules/@redis/client/dist/lib/commands/XPENDING.d.ts:13:1 - error TS1128: Declaration or statement expected.

13 ];
   ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:10:7 - error TS1005: ',' expected.

10     id: RedisCommandArgument,
         ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:11:13 - error TS1005: ';' expected.

11     consumer: RedisCommandArgument,
               ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:12:34 - error TS1005: ';' expected.

12     millisecondsSinceLastDelivery: number,
                                    ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:13:22 - error TS1005: ';' expected.

13     deliveriesCounter: number
                        ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:14:1 - error TS1128: Declaration or statement expected.

14 ]>;
   ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:14:2 - error TS1109: Expression expected.

14 ]>;
    ~

../node_modules/@redis/client/dist/lib/commands/XPENDING_RANGE.d.ts:14:3 - error TS1109: Expression expected.

14 ]>;
     ~

../node_modules/@redis/client/dist/lib/commands/ZMPOP.d.ts:6:8 - error TS1005: ',' expected.

6     key: string,
         ~

../node_modules/@redis/client/dist/lib/commands/ZMPOP.d.ts:7:13 - error TS1005: ',' expected.

7     elements: Array<[RedisCommandArgument, RedisCommandArgument]>
              ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:143:9 - error TS1005: ',' expected.

143     name: string,
            ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:144:10 - error TS1005: ',' expected.

144     arity: number,
             ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:145:10 - error TS1005: ',' expected.

145     flags: Array<CommandFlags>,
             ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:146:18 - error TS1005: ',' expected.

146     firstKeyIndex: number,
                     ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:147:17 - error TS1005: ',' expected.

147     lastKeyIndex: number,
                    ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:148:9 - error TS1005: ',' expected.

148     step: number,
            ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:149:15 - error TS1005: ',' expected.

149     categories: Array<CommandCategories>
                  ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:209:10 - error TS1005: ',' expected.

209     start: number,
             ~

../node_modules/@redis/client/dist/lib/commands/generic-transformers.d.ts:210:8 - error TS1005: ',' expected.

210     end: number
           ~

../node_modules/@redis/client/dist/lib/commands/index.d.ts:20:231 - error TS1005: ',' expected.

20 export declare type RedisCommandSignature<Command extends RedisCommand, Params extends Array<unknown> = Parameters<Command['transformArguments']>> = <Options extends CommandOptions<ClientCommandOptions>>(...args: Params | [options: Options, ...rest: Params]) => Promise<ConvertArgumentType<RedisCommandReply<Command>, Options['returnBuffers'] extends true ? Buffer : string>>;
                                                                                                                                                                                                                                         ~

../node_modules/@redis/client/dist/lib/commands/index.d.ts:20:249 - error TS1005: ',' expected.

20 export declare type RedisCommandSignature<Command extends RedisCommand, Params extends Array<unknown> = Parameters<Command['transformArguments']>> = <Options extends CommandOptions<ClientCommandOptions>>(...args: Params | [options: Options, ...rest: Params]) => Promise<ConvertArgumentType<RedisCommandReply<Command>, Options['returnBuffers'] extends true ? Buffer : string>>;
                                                                                                                                                                                                                                                           ~

../node_modules/@redis/graph/dist/commands/CONFIG_GET.d.ts:4:14 - error TS1005: ',' expected.

4     configKey: string,
               ~

../node_modules/@redis/graph/dist/commands/CONFIG_GET.d.ts:5:10 - error TS1005: ',' expected.

5     value: number
           ~

../node_modules/@redis/graph/dist/commands/QUERY.d.ts:8:12 - error TS1005: ',' expected.

8     headers: Headers,
             ~

../node_modules/@redis/graph/dist/commands/QUERY.d.ts:9:9 - error TS1005: ',' expected.

9     data: Data,
          ~

../node_modules/@redis/graph/dist/commands/QUERY.d.ts:10:13 - error TS1005: ',' expected.

10     metadata: Metadata
               ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:5:14 - error TS1005: ',' expected.

5     timestamp: string,
               ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:6:12 - error TS1005: ';' expected.

6     command: string,
             ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:7:10 - error TS1005: ';' expected.

7     query: string,
           ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:8:9 - error TS1005: ';' expected.

8     took: string
          ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:9:1 - error TS1128: Declaration or statement expected.

9 ]>;
  ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:9:2 - error TS1109: Expression expected.

9 ]>;
   ~

../node_modules/@redis/graph/dist/commands/SLOWLOG.d.ts:9:3 - error TS1109: Expression expected.

9 ]>;
    ~

../node_modules/@redis/json/dist/commands/STRAPPEND.d.ts:2:36 - error TS1005: ',' expected.

2 declare type AppendArguments = [key: string, append: string];
                                     ~

../node_modules/@redis/json/dist/commands/STRAPPEND.d.ts:2:52 - error TS1005: ',' expected.

2 declare type AppendArguments = [key: string, append: string];
                                                     ~

../node_modules/@redis/json/dist/commands/STRAPPEND.d.ts:3:44 - error TS1005: ',' expected.

3 declare type AppendWithPathArguments = [key: string, path: string, append: string];
                                             ~

../node_modules/@redis/json/dist/commands/STRAPPEND.d.ts:3:58 - error TS1005: ',' expected.

3 declare type AppendWithPathArguments = [key: string, path: string, append: string];
                                                           ~

../node_modules/@redis/json/dist/commands/STRAPPEND.d.ts:3:74 - error TS1005: ',' expected.

3 declare type AppendWithPathArguments = [key: string, path: string, append: string];
                                                                           ~

../node_modules/@redis/search/dist/commands/AGGREGATE.d.ts:108:10 - error TS1005: ',' expected.

108     total: number,
             ~

../node_modules/@redis/search/dist/commands/AGGREGATE.d.ts:109:15 - error TS1005: ',' expected.

109     ...results: Array<Array<RedisCommandArgument>>
                  ~

../node_modules/@redis/search/dist/commands/AGGREGATE_WITHCURSOR.d.ts:8:11 - error TS1005: ',' expected.

8     result: AggregateRawReply,
            ~

../node_modules/@redis/search/dist/commands/AGGREGATE_WITHCURSOR.d.ts:9:11 - error TS1005: ',' expected.

9     cursor: number
            ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:12:6 - error TS1005: ',' expected.

12     _: string,
        ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:13:9 - error TS1005: ';' expected.

13     term: string,
           ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:14:16 - error TS1005: ';' expected.

14     suggestions: Array<[score: string, suggestion: string]>
                  ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:14:30 - error TS1005: ',' expected.

14     suggestions: Array<[score: string, suggestion: string]>
                                ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:14:50 - error TS1005: ',' expected.

14     suggestions: Array<[score: string, suggestion: string]>
                                                    ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:15:1 - error TS1109: Expression expected.

15 ]>;
   ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:15:2 - error TS1109: Expression expected.

15 ]>;
    ~

../node_modules/@redis/search/dist/commands/SPELLCHECK.d.ts:15:3 - error TS1109: Expression expected.

15 ]>;
     ~

../node_modules/@redis/search/dist/commands/index.d.ts:132:36 - error TS1110: Type expected.

132 export declare type PropertyName = `${'@' | '$.'}${string}`;
                                       ~~~

../node_modules/@redis/search/dist/commands/index.d.ts:214:12 - error TS1005: ',' expected.

214     results: T,
               ~

../node_modules/@redis/search/dist/commands/index.d.ts:215:12 - error TS1005: ',' expected.

215     profile: [
               ~

../node_modules/@redis/search/dist/commands/index.d.ts:216:10 - error TS1005: ',' expected.

216         _: string,
             ~

../node_modules/@redis/search/dist/commands/index.d.ts:217:25 - error TS1005: ',' expected.

217         TotalProfileTime: string,
                            ~

../node_modules/@redis/search/dist/commands/index.d.ts:218:10 - error TS1005: ',' expected.

218         _: string,
             ~

../node_modules/@redis/search/dist/commands/index.d.ts:219:20 - error TS1005: ',' expected.

219         ParsingTime: string,
                       ~

../node_modules/@redis/search/dist/commands/index.d.ts:220:10 - error TS1005: ',' expected.

220         _: string,
             ~

../node_modules/@redis/search/dist/commands/index.d.ts:221:29 - error TS1005: ',' expected.

221         PipelineCreationTime: string,
                                ~

../node_modules/@redis/search/dist/commands/index.d.ts:222:10 - error TS1005: ',' expected.

222         _: string,
             ~

../node_modules/@redis/search/dist/commands/index.d.ts:223:25 - error TS1005: ',' expected.

223         IteratorsProfile: Array<any>
                            ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:6:6 - error TS1005: ',' expected.

6     _: string,
       ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:7:17 - error TS1005: ',' expected.

7     totalSamples: number,
                  ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:8:6 - error TS1005: ',' expected.

8     _: string,
       ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:9:16 - error TS1005: ',' expected.

9     memoryUsage: number,
                 ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:10:6 - error TS1005: ',' expected.

10     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:11:19 - error TS1005: ',' expected.

11     firstTimestamp: number,
                     ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:12:6 - error TS1005: ',' expected.

12     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:13:18 - error TS1005: ',' expected.

13     lastTimestamp: number,
                    ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:14:6 - error TS1005: ',' expected.

14     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:15:18 - error TS1005: ',' expected.

15     retentionTime: number,
                    ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:16:6 - error TS1005: ',' expected.

16     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:17:15 - error TS1005: ',' expected.

17     chunkCount: number,
                 ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:18:6 - error TS1005: ',' expected.

18     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:19:14 - error TS1005: ',' expected.

19     chunkSize: number,
                ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:20:6 - error TS1005: ',' expected.

20     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:21:14 - error TS1005: ',' expected.

21     chunkType: string,
                ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:22:6 - error TS1005: ',' expected.

22     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:23:20 - error TS1005: ',' expected.

23     duplicatePolicy: TimeSeriesDuplicatePolicies | null,
                      ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:24:6 - error TS1005: ',' expected.

24     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:25:11 - error TS1005: ',' expected.

25     labels: Array<[name: string, value: string]>,
             ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:25:24 - error TS1005: ',' expected.

25     labels: Array<[name: string, value: string]>,
                          ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:25:39 - error TS1005: ',' expected.

25     labels: Array<[name: string, value: string]>,
                                         ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:25:48 - error TS1005: ';' expected.

25     labels: Array<[name: string, value: string]>,
                                                  ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:25:49 - error TS1109: Expression expected.

25     labels: Array<[name: string, value: string]>,
                                                   ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:26:6 - error TS1005: ';' expected.

26     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:27:14 - error TS1005: ';' expected.

27     sourceKey: string | null,
                ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:28:6 - error TS1005: ';' expected.

28     _: string,
        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:29:10 - error TS1005: ';' expected.

29     rules: Array<[key: string, timeBucket: number, aggregationType: TimeSeriesAggregationType]>
            ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:29:22 - error TS1005: ',' expected.

29     rules: Array<[key: string, timeBucket: number, aggregationType: TimeSeriesAggregationType]>
                        ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:29:42 - error TS1005: ',' expected.

29     rules: Array<[key: string, timeBucket: number, aggregationType: TimeSeriesAggregationType]>
                                            ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:29:67 - error TS1005: ',' expected.

29     rules: Array<[key: string, timeBucket: number, aggregationType: TimeSeriesAggregationType]>
                                                                     ~

../node_modules/@redis/time-series/dist/commands/INFO.d.ts:30:1 - error TS1109: Expression expected.

30 ];
   ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:5:16 - error TS1005: ',' expected.

5     ...infoArgs: InfoRawReply,
                 ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:6:6 - error TS1005: ',' expected.

6     _: string,
       ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:7:16 - error TS1005: ',' expected.

7     keySelfName: string,
                 ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:8:6 - error TS1005: ',' expected.

8     _: string,
       ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:9:11 - error TS1005: ',' expected.

9     chunks: Array<[
            ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:10:10 - error TS1005: ',' expected.

10         _: string,
            ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:11:23 - error TS1005: ',' expected.

11         startTimestamp: number,
                         ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:12:10 - error TS1005: ',' expected.

12         _: string,
            ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:13:21 - error TS1005: ',' expected.

13         endTimestamp: number,
                       ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:14:10 - error TS1005: ',' expected.

14         _: string,
            ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:15:16 - error TS1005: ',' expected.

15         samples: number,
                  ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:16:10 - error TS1005: ',' expected.

16         _: string,
            ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:17:13 - error TS1005: ',' expected.

17         size: number,
               ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:18:10 - error TS1005: ',' expected.

18         _: string,
            ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:19:23 - error TS1005: ',' expected.

19         bytesPerSample: string
                         ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:20:6 - error TS1005: ';' expected.

20     ]>
        ~

../node_modules/@redis/time-series/dist/commands/INFO_DEBUG.d.ts:21:1 - error TS1109: Expression expected.

21 ];
   ~

../node_modules/@redis/time-series/dist/commands/MGET.d.ts:6:8 - error TS1005: ',' expected.

6     key: string,
         ~

../node_modules/@redis/time-series/dist/commands/MGET.d.ts:7:11 - error TS1005: ';' expected.

7     labels: RawLabels,
            ~

../node_modules/@redis/time-series/dist/commands/MGET.d.ts:8:11 - error TS1005: ';' expected.

8     sample: SampleRawReply
            ~

../node_modules/@redis/time-series/dist/commands/MGET.d.ts:9:1 - error TS1128: Declaration or statement expected.

9 ]>;
  ~

../node_modules/@redis/time-series/dist/commands/MGET.d.ts:9:2 - error TS1109: Expression expected.

9 ]>;
   ~

../node_modules/@redis/time-series/dist/commands/MGET.d.ts:9:3 - error TS1109: Expression expected.

9 ]>;
    ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:104:45 - error TS1005: ',' expected.

104 export declare type RawLabels = Array<[label: string, value: string]>;
                                                ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:104:60 - error TS1005: ';' expected.

104 export declare type RawLabels = Array<[label: string, value: string]>;
                                                               ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:104:68 - error TS1005: ';' expected.

104 export declare type RawLabels = Array<[label: string, value: string]>;
                                                                       ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:104:69 - error TS1109: Expression expected.

104 export declare type RawLabels = Array<[label: string, value: string]>;
                                                                        ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:104:70 - error TS1109: Expression expected.

104 export declare type RawLabels = Array<[label: string, value: string]>;
                                                                         ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:118:48 - error TS1005: ',' expected.

118 export declare type SampleRawReply = [timestamp: number, value: string];
                                                   ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:118:63 - error TS1005: ',' expected.

118 export declare type SampleRawReply = [timestamp: number, value: string];
                                                                  ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:157:8 - error TS1005: ',' expected.

157     key: string,
           ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:158:11 - error TS1005: ';' expected.

158     labels: RawLabels,
              ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:159:12 - error TS1005: ';' expected.

159     samples: Array<SampleRawReply>
               ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:160:1 - error TS1005: '(' expected.

160 ]>;
    ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:160:2 - error TS1109: Expression expected.

160 ]>;
     ~

../node_modules/@redis/time-series/dist/commands/index.d.ts:160:3 - error TS1109: Expression expected.

160 ]>;
      ~


Found 506 errors.
```


**Environment:**
 - **Node.js Version**: 18.8.0
 - **Redis Server Version**: 7.0.4
 - **Node Redis Version**: 
 ```
redis-test@1.0.0 /home/ali/redis-test
└── redis@4.3.1
```
 - **Platform**: Ubuntu 20.04.3

**Comment by leibale** [comment]
which TypeScript version are you using? I'm pretty sure that the minimum version that works with this package is 4.2
