### ISSUE TITLE
client.batch is not a function

### ISSUE THREAD

**Issue by kokjurrien** [redis/node-redis#1796]
When updating from v3->v4 I can no longer use the batch() function on the redisClient object.

The migration guide makes no reference of this being unsupported.

setting legacyMode to true does not resolve this.

**Environment:**
 - **Node.js Version**: v14" -->
 - **Node Redis Version**: 4.0.1

**Comment by leibale** [comment]
We definitely need to add it to the migration guide and changelog (I'll leave this issue open until we'll do it), but:
1.  As [described here](https://github.com/redis/node-redis/blob/master/docs/FAQ.md#how-are-commands-batched), commands from the same "event loop tick" will be sent "batched" anyway.
2.  In case you use `.batch` as a way to queue commands and execute them later, you can do:
```javascript
const [getReply, setReply] = await client.multi()
  .get('1')
  .set('2', '2')
  .execAsPipeline();

// you can "save" a "multi" instance and use it later
const multi = client.multi();
process.on('message', message => {
  if (message === 'EXEC') {
    return multi.execAsPipeline();
  }

  multi.sAdd('messages', message);
});
```
