### ISSUE TITLE
Version 4 missing multi().select

### ISSUE THREAD

**Issue by ItzRabbs** [redis/node-redis#2046]
`multi().select` no longer works after upgrading to v4 from v3.

`Property 'select' does not exist on type 'RedisClientMultiCommandType<{ graph: { CONFIG_GET: typeof import("d:/Code/ProRank/code/coreservices-node/node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("d:/Code/ProRank/code/coreservices-node/node_modules/@node-redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typ...'.`

**Environment:**
 - **Node.js Version**: v16.14.1
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.4
 - **Platform**: Windows 10

**Comment by Didas-git** [comment]
Maybe the solution at #1989 might help you

**Comment by ItzRabbs** [comment]
Sorry, looks like my title was wrong. I have `redis.mult()`. What I get an error on is `redis.multi().select`.

**Comment by ItzRabbs** [comment]
I could be wrong, but I don't think the solution in https://github.com/redis/node-redis/issues/1989 fixes this issue

**Comment by leibale** [comment]
Using the `SELECT` commands effects all the commands afterwords (even if the `SELECT` command is within  `MULTI` context):
```javascript
client.multi()
  .select(2)
  .exec();

client.set('a', 'b'); // will set the key a under db 2, even though the `SELECT` command is in the multi context
```

(I'm not saying this is not a valid bug/feature request, just that I don't think you'll want to use it...)

**Comment by ItzRabbs** [comment]
> Using the `SELECT` commands effects all the commands afterwords (even if the `SELECT` command is within  `MULTI` context):
> ```javascript
> client.multi()
>   .select(2)
>   .exec();
> 
> client.set('a', 'b'); // will set the key a under db 2, even though the `SELECT` command is in the multi context
> ```
> 
> (I'm not saying this is not a valid bug/feature request, just that I don't think you'll want to use it...)

That is the conditions I want to use it in.

**Comment by ItzRabbs** [comment]
Oh, I didn't realize there is a `.addCommand(['SELECT', '1'])`. I'll have to check it out.

The most I can share about my use case is that I need to run commands (mostly get and set) in multiple databases at the same time. So like...

```
SELECT 1
GET abc
SELECT 2
GET def
etc...
```

It is odd to me why `mult().select` was even removed in version 4 if it existed in version 3. I wasn't able to find anything on why it was removed, so it seems like just an oversight perhaps?

**Comment by leibale** [comment]
yea, it was removed by a mistake, and will be added back soon

**Comment by ItzRabbs** [comment]
Any update on this?

**Comment by leibale** [comment]
@ItzRabbs wanna try #2133?

**Comment by ItzRabbs** [comment]
Yes, though I'm away from my computer for a few days. I'll try it out the moment I can.

**Comment by ItzRabbs** [comment]
Can a new npm release be created with this patch?

**Comment by leibale** [comment]
@ItzRabbs sorry about the long delay, I was on vacation... I'll release it this week.

**Comment by ItzRabbs** [comment]
@leibale no worries, thank you

**Comment by ItzRabbs** [comment]
@leibale Any chance for a new release soon?

**Comment by leibale** [comment]
@ghost `redis@4.1.1` & `@redis/cliet@1.1.1` is on NPM :tada:

**Comment by fast-facts** [comment]
It doesn't look like this is fixed

```js
const { host, port } = { host: '<enter the right host name in here>', port: 6379 };

import { createClient } from 'redis';

void (async () => {
  const client = createClient({
    url: `redis://${host}:${port}`
  });

  await client.multi().set('foo', 'bar').exec();
  await client.multi().select(1).exec();
})();
```

```
test.ts:11:24 - error TS2339: Property 'select' does not exist on type 'RedisClientMultiCommandType<{ graph: { CONFIG_GET: typeof import("D:/Code/ProRank/code/coreservices-node/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("D:/Code/ProRank/code/coreservices-node/node_modules/@redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import...'.

11   await client.multi().select(1).exec();
```
