### ISSUE TITLE
Version 4 missing multi().select

### ISSUE THREAD

**Issue by fast-facts** [redis/node-redis#2177]
Follow up on https://github.com/redis/node-redis/issues/2046 where multi().select wasn't working. It doesn't look like this is fixed in 4.1.1.

```js
const { host, port } = { host: '<enter the right host name in here>', port: 6379 };

import { createClient } from 'redis';

void (async () => {
  const client = createClient({
    url: `redis://${host}:${port}`
  });

  await client.multi().set('foo', 'bar').exec();
  await client.multi().select(1).exec();
})();
```

```
test.ts:11:24 - error TS2339: Property 'select' does not exist on type 'RedisClientMultiCommandType<{ graph: { CONFIG_GET: typeof import("D:/Code/ProRank/code/coreservices-node/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("D:/Code/ProRank/code/coreservices-node/node_modules/@redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import...'.

11   await client.multi().select(1).exec();
```

**Comment by leibale** [comment]
I'm not too sure why its not in `redis@4.1.1`/`@node-redis/client@1.1.1`, but `client.multi().select(1).exec()` works with `redis@4.2.0`/`@redis/client@1.2.0`
